name: Auto Project Card Mover

on:
  pull_request:
    types: [opened, closed, reopened, ready_for_review]

jobs:
  update-project-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to In Review or Done
        uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: Ear Trainer Roadmap
          column: ${{ github.event.action == 'closed' && 'Done' || 'In Review' }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
